server:
  port: 8081
spring:
  application:
    name: stockservice
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public
      server-addr: 127.0.0.1:8848